model:
  backbone:
#    [
#      [ -1, TinyStage, 1, [ 3, 48, 3, 2, 1] ],
#      [ -1, TinyStage, 2, [ 48, 48, 3, 2, 1, 48] ],
#      [ -1, TinyStage, 3, [ 48, 96, 3, 2, 1, 48] ],
#      [ -1, TinyStage, 3, [ 96, 192, 3, 2, 1, 96] ],
#      [ -1, TinyStage, 1, [ 192, 1280, 3, 2, 1] ],  # args: [c_in, c_out, stride, block]  insert n to index 2.
#    ]
    [
      [ -1, TinyStage, 1, [ 3, 64, 3, 2, 1] ],
      [ -1, TinyStage, 2, [ 64, 64, 3, 2, 1, 64] ],
      [ -1, TinyStage, 3, [ 64, 128, 3, 2, 1, 64] ],
      [ -1, TinyStage, 4, [ 128, 256, 3, 2, 1, 128] ],
      [ -1, TinyStage, 2, [ 256, 512, 3, 2, 1, 256] ],  # args: [c_in, c_out, stride, block]  insert n to index 2.
    ]

  neck:
    [
      [ -1, nn.Conv2d, 1, [ 512, 256, 1, 1 ] ],
      [ [ -1, 3 ], FPNBlock, 1, [ 256, 256, 1, 1 ] ],
      [ [ -1, 2 ], FPNBlock, 1, [ 128, 256, 1, 1 ] ],
      [ -1, nn.Conv2d, 1, [ 256, 256, 3, 1, 1 ] ],
      [ 6, nn.Conv2d, 1, [ 256, 256, 3, 1, 1 ] ],
      [ 5, nn.Conv2d, 1, [ 256, 256, 3, 1, 1 ] ],
      [ -1, nn.Conv2d, 1, [ 256, 256, 3, 2, 1 ] ],
      [ -1, nn.Conv2d, 1, [ 256, 256, 3, 2, 1 ] ]
    ]

  head:
    [
      [ [ 8, 9, 10, 11, 12 ], RetinaHead, 1, [ 256, 256, False, 4, 20, 9]]  # c1, c2, dbb, convs, nc, na
    ]


optimizer:
  cfg: 'SGD'
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001


dataset:
  base:
    cfg: 'VOCDataset'
    CLASSES_NAME: [ "__background__ ","aeroplane","bicycle","bird","boat","bottle","bus","car","cat","chair","cow","diningtable","dog",
                    "horse","motorbike","person","pottedplant","sheep","sofa","train","tvmonitor" ]
#    CLASSES_NAME: [ "__background__ ",'straight_strut','curved_strut','key_pieces','chain_buckle','spacer','metal_cover','hinge',
#                    'plastic_cover','curved_copper_nozzle','u-copper_tube','connector','fixings','blade','shim',
#                    'notched_ring_cap','plastic_inserts','long_magnetic_sheet','short_magnetic_sheet',
#                    'rectangular_gasket','u-shape_bridge' ]
    img_sizes: [512, 640]
    root_dir: '/home/richard/Datasets/VOCdevkit'
  train:
    batch_size: 4
    is_train: True
    set_: "[('2007', 'trainval'), ('2012', 'trainval')]"
  eval:
    batch_size: 2
    is_train: False
    set_: "[('2007', 'test')]"

loss:
  cfg: 'retina_loss'
  cls_loss:
    cfg: 'focal_loss'
    alpha: 0.25
    gamma: 2.0
  reg_loss:
    cfg: 'CIoU'

generator:
  cfg: 'Anchor_Gen'
  strides: [8, 16, 32, 64, 128]
  ratios: [0.5, 1, 2]
  scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  base_sizes: [16, 32, 64, 128, 256]
  scale_major: True
  #centers: None,
  center_offset: 0.
#generator:
#  cfg: 'YOLOAnchorGen'
#  strides: [8, 16, 32]
#  base_sizes: '[[(10, 13), (16, 30), (33, 23)],
#                [(30, 61), (62, 45), (59, 119)],
#                [(116, 90), (156, 198), (373, 326)]]'
cfg: 'rep-fpn-gs-gf'