

model:
  backbone:
    # [from, number, module, args]
    [
     [-1, ConvBN, 1, [3, 32, 6, 2, 2]],  # 0
     [-1, RepVGGStage, 1, [32, 64, 3, 2, 1]],  # 1
     [-1, C3, 1, [64, 64]],
     [-1, RepVGGStage, 1, [64, 128, 3, 2, 1]], # 3
     [-1, C3, 2, [128, 128]],
     [-1, RepVGGStage, 1, [128, 256, 3, 2, 1]], # 5
     [-1, C3, 3, [256, 256]],
     [-1, RepVGGStage, 1, [256, 512, 3, 2, 1]], # 7
     [-1, C3, 1, [512, 512, False]],
     [-1, SPPF, 1, [512, 512]], # 9
    ]

  # YOLOv5 neck
  neck:
    [
     [-1, ConvBN, 1, [512, 128, 1, 1]],
     [-1, nn.Upsample, 1, [None, 2, 'nearest']],
     [[-1, 6], Concat, 1, [1]],
     [-1, C3, 1, [384, 128, False]],  # 13

     [-1, ConvBN, 1, [128, 128, 1, 1]],
     [-1, nn.Upsample, 1, [None, 2, 'nearest']],
     [[-1, 4], Concat, 1, [1]],
     [-1, C3, 3, [256, 128, False]],  # 17 (P3/8-small)

     [-1, ConvBN, 1, [128, 128, 3, 2, 1]],
     [[-1, 14], Concat, 1, [1]],
     [-1, C3, 3, [256, 128, False]],  # 20 (P4/16-medium)

     [-1, ConvBN, 1, [128, 128, 3, 2, 1]],
     [[-1, 10], Concat, 1, [1]],
     [-1, C3, 3, [256, 128, False]]  # 23 (P5/32-large)
    ]

  head:
    [
      [ [17, 20, 23], RetinaHead, 1, [ 128, 128, False, 4, 20, 9]]  # c1, c2, dbb, convs, nc, na
    ]


optimizer:
  cfg: 'SGD'
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001


dataset:
  base:
    cfg: 'VOCDataset'
    CLASSES_NAME: [ "__background__ ","aeroplane","bicycle","bird","boat","bottle","bus","car","cat","chair","cow","diningtable","dog",
                    "horse","motorbike","person","pottedplant","sheep","sofa","train","tvmonitor" ]
#    CLASSES_NAME: [ "__background__ ",'straight_strut','curved_strut','key_pieces','chain_buckle','spacer','metal_cover','hinge',
#                    'plastic_cover','curved_copper_nozzle','u-copper_tube','connector','fixings','blade','shim',
#                    'notched_ring_cap','plastic_inserts','long_magnetic_sheet','short_magnetic_sheet',
#                    'rectangular_gasket','u-shape_bridge' ]
    img_sizes: [512, 640]
    root_dir: '/home/richard/Datasets/VOCdevkit_wp'
  train:
    batch_size: 4
    is_train: True
    set_: "[('2022', 'trainval')]"
  eval:
    batch_size: 2
    is_train: False
    set_: "[('2022', 'test')]"

loss:
  cfg: 'retina_loss'
  cls_loss:
    cfg: 'focal_loss'
    alpha: 0.25
    gamma: 2.0
  reg_loss:
    cfg: 'smooth_l1'

generator:
  cfg: 'Anchor_Gen'
  strides: [8, 16, 32]
  ratios: [0.5, 1, 2]
  scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  base_sizes: [16, 32, 64]
  scale_major: True
  #centers: None,
  center_offset: 0.
#generator:
#  cfg: 'YOLOAnchorGen'
#  strides: [8, 16, 32]
#  base_sizes: '[[(10, 13), (16, 30), (33, 23)],
#                [(30, 61), (62, 45), (59, 119)],
#                [(116, 90), (156, 198), (373, 326)]]'
cfg: 'retina-pan-lite-g'
